-- Clear out existing tables
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS `auth`;

CREATE TABLE `auth` (
  token_id VARCHAR NOT NULL PRIMARY KEY,
  username VARCHAR NOT NULL
);

CREATE TABLE people (
  uuid VARCHAR NOT NULL PRIMARY KEY,
  descendant VARCHAR NOT NULL,
  first_name VARCHAR NOT NULL,
  last_name VARCHAR NOT NULL,
  gender VARCHAR(1) NOT NULL,
  father VARCHAR,
  mother VARCHAR,
  spouse VARCHAR
);

CREATE TABLE users (
  username VARCHAR NOT NULL PRIMARY KEY,
  password VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  firstName VARCHAR NOT NULL,
  lastName VARCHAR NOT NULL,
  gender VARCHAR(1),
  person_id VARCHAR NOT NULL
);

CREATE TABLE events (
  id VARCHAR NOT NULL PRIMARY KEY,
  descendant VARCHAR NOT NULL,
  person VARCHAR NOT NULL,
  location INTEGER NOT NULL,
  type VARCHAR,
  year INTEGER
);

CREATE TABLE locations (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  country VARCHAR NOT NULL,
  city VARCHAR NOT NULL
);


